<?php

class phpbb3_user extends bors_object_db
{
	function storage_engine() { return 'bors_storage_mysql'; }
	function db_name() { return 'AB_WEBAPPS_PHPBB3'; }
	function table_name() { return 'phpbb_users'; }

	function class_title() { return ec('Пользователь'); }

	function table_fields()
	{
		return array(
			'id' => 'user_id',
			'user_type',
			'group_id',
			'user_permissions',
			'user_perm_from',
			'user_ip',
			'user_regdate',
			'username',
			'username_clean',
			'user_password',
			'user_passchg',
			'user_pass_convert',
			'user_email',
			'user_email_hash',
			'user_birthday',
			'user_lastvisit',
			'user_lastmark',
			'user_lastpost_time',
			'user_lastpage',
			'user_last_confirm_key',
			'user_last_search',
			'user_warnings',
			'user_last_warning',
			'user_login_attempts',
			'user_inactive_reason',
			'user_inactive_time',
			'user_posts',
			'user_lang',
			'user_timezone',
			'user_dst',
			'user_dateformat',
			'user_style',
			'user_rank',
			'user_colour',
			'user_new_privmsg',
			'user_unread_privmsg',
			'user_last_privmsg',
			'user_message_rules',
			'user_full_folder',
			'user_emailtime',
			'user_topic_show_days',
			'user_topic_sortby_type',
			'user_topic_sortby_dir',
			'user_post_show_days',
			'user_post_sortby_type',
			'user_post_sortby_dir',
			'user_notify',
			'user_notify_pm',
			'user_notify_type',
			'user_allow_pm',
			'user_allow_viewonline',
			'user_allow_viewemail',
			'user_allow_massemail',
			'user_options',
			'user_avatar',
			'user_avatar_type',
			'user_avatar_width',
			'user_avatar_height',
			'user_sig',
			'user_sig_bbcode_uid',
			'user_sig_bbcode_bitfield',
			'user_from',
			'user_icq',
			'user_aim',
			'user_yim',
			'user_msnm',
			'user_jabber',
			'user_website',
			'user_occ' => array('type' => 'bbcode'),
			'user_interests' => array('type' => 'bbcode'),
			'user_actkey',
			'user_newpasswd',
			'user_form_salt',
			'user_new',
			'user_reminded',
			'user_reminded_time',
			'user_wpuint_id',
			'user_wpublog_id',
		);
	}
}
